# Generated by Django 4.1.6 on 2023-02-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0003_alter_catagory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='slug',
            field=models.SlugField(),
        ),
    ]
