# Generated by Django 4.1.6 on 2023-02-20 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0004_alter_catagory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='LittlelemonAPI.catagory'),
        ),
    ]
